#[{a:7},"Esc","Q","W","E","R","T",{x:2},"Y","U","I","O","P","Bspc"],
#["Tab","A","S","D","F","G",{x:2},"H","J","K","L",";","Enter"],
#[{sm:"cherry",a:5,f2:1},"\nSteno\n\n\n\n\nLayer",{sm:"",a:7},"Z","X","C","V","B",{x:2},"N","M",{a:5,f:3},"\n,\n\n\n\n\n<",{f:3},"\n.\n\n\n\n\n>",{f:3},"\n/\n\n\n\n\n?",{f2:1},"\nNmbrs\n\n\n\n\nLayer"],
#[{x:3,f:3},"\nCmd\n\n\n\n\nWIn/",{a:7},"Cntrl","Space",{x:2},"Shift",{a:5,f2:1},"\nMouse\n\n\n\n\nLayer",{a:7},""]
[keyboard]
name = "Kiwi Board"
product_name = "Kiwi Board"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "manni"
chip = "rp2040"

[matrix]
input_pins = ["PIN_12", "PIN_13", "PIN_14", "PIN_15"]
output_pins = ["PIN_0", "PIN_1", "PIN_2", "PIN_3", "PIN_4", "PIN_5", "PIN_6", "PIN_7", "PIN_8", "PIN_9", "PIN_10", "PIN_11"]

[layout]
rows = 4
cols = 12
layers = 2
keymap = [
    [
        ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L"],
        ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L"],
        ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L"],
        ["_", "_", "_", "D", "E", "F", "G", "H", "I", "_", "_", "_"],
    ],
]

[lightning]
[storage]
